### ISSUE TITLE
Consulta Artes Marciales

### ISSUE THREAD

**Issue by FrancoGiachetta27** [pdepjm/2023-tp0-presentacion-micaela-Aguero#4]
Cuál de todas practicas? Yo hice Tae-kwon-do por 5 años, pero lo terminé dejando por cabeza dura.

**Comment by micaela-Aguero** [comment]
Bujutsu, no la conocía hasta que empecé a practicarla la verdad jaja
Volverías a entrenar?

**Comment by FrancoGiachetta27** [comment]
Wow que nombre raro jaja, es del estilo ese que hacen danzas medio para meditar? Hablo desde la ignorancia pura, tal vez dije cualquiera. A veces me sorprendo de la cantidad de tipos que hay. Y sí, estaría bueno arrancar a entrenar otra vez.

**Comment by micaela-Aguero** [comment]
En realidad no jaja en si se divide en tres partes: katas, defensas personales y armas, es japonesa :)
